### ISSUE TITLE
Если решил делать классом, то делай методы статическими( и почему все-таки классом)?

### ISSUE THREAD

**Issue by didolf** [buza94s/movies-app#2]
https://github.com/buza94s/movies-app/blob/e7bb9a7a326304450352c20010bf7571be36b69b/src/system/HelperFunction.js#L2

**Comment by didolf** [comment]
https://github.com/buza94s/movies-app/blob/e7bb9a7a326304450352c20010bf7571be36b69b/src/system/Api.js#L2 - тот же вопрос

**Comment by buza94s** [comment]
Переделал, убрал класс, оставил просто функции. Почему сделал классом уже не скажу)) возможно в видосах так делали, но это не точно
