### ISSUE TITLE
Обычно такие ссылки длинные и прячут в ApiService, сейчас он достаточно бестолковый

### ISSUE THREAD

**Issue by didolf** [buza94s/movies-app#3]
https://github.com/buza94s/movies-app/blob/e7bb9a7a326304450352c20010bf7571be36b69b/src/components/App/App.jsx#L34

**Comment by didolf** [comment]
https://github.com/buza94s/movies-app/blob/e7bb9a7a326304450352c20010bf7571be36b69b/src/components/App/App.jsx#L40

**Comment by didolf** [comment]
https://github.com/buza94s/movies-app/blob/e7bb9a7a326304450352c20010bf7571be36b69b/src/components/App/App.jsx#L56

**Comment by buza94s** [comment]
поправил
